"""Tests for the soapix code generator."""

from __future__ import annotations

from pathlib import Path

import pytest

from soapix.codegen.generator import ClientGenerator
from soapix.wsdl.parser import WsdlParser

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def simple_code():
    doc = WsdlParser().load(str(FIXTURES / "simple.wsdl"))
    return ClientGenerator(doc).generate(str(FIXTURES / "simple.wsdl"))


@pytest.fixture
def gib_code():
    doc = WsdlParser().load(str(FIXTURES / "gib_efatura.wsdl"))
    return ClientGenerator(doc).generate(str(FIXTURES / "gib_efatura.wsdl"))


@pytest.fixture
def xs_attribute_code():
    doc = WsdlParser().load(str(FIXTURES / "xs_attribute.wsdl"))
    return ClientGenerator(doc).generate(str(FIXTURES / "xs_attribute.wsdl"))


class TestGeneratedCodeIsValidPython:
    def test_simple_compiles(self, simple_code):
        compile(simple_code, "<generated>", "exec")

    def test_gib_compiles(self, gib_code):
        compile(gib_code, "<generated>", "exec")

    def test_xs_attribute_compiles(self, xs_attribute_code):
        compile(xs_attribute_code, "<generated>", "exec")


class TestGeneratedCodeStructure:
    def test_has_header_comment(self, simple_code):
        assert "# Generated by soapix" in simple_code

    def test_has_future_import(self, simple_code):
        assert "from __future__ import annotations" in simple_code

    def test_has_soapix_import(self, simple_code):
        assert "from soapix import SoapClient" in simple_code

    def test_has_client_class(self, simple_code):
        assert "class UserServiceClient:" in simple_code

    def test_has_init_method(self, simple_code):
        assert "def __init__(self" in simple_code
        assert "SoapClient(wsdl" in simple_code

    def test_has_operations(self, simple_code):
        assert "def GetUser(" in simple_code
        assert "def CreateUser(" in simple_code

    def test_required_param_no_default(self, simple_code):
        # userId is required — should have no default value
        assert "userId: int," in simple_code or "userId: int\n" in simple_code

    def test_optional_param_has_none_default(self, simple_code):
        # locale is optional
        assert "= None" in simple_code

    def test_return_type_is_dict(self, simple_code):
        assert "-> dict:" in simple_code

    def test_calls_underlying_service(self, simple_code):
        assert "self._client.service." in simple_code


class TestComplexTypeDataclass:
    def test_complex_type_generates_dataclass(self, xs_attribute_code):
        assert "@dataclass" in xs_attribute_code
        assert "from dataclasses import dataclass" in xs_attribute_code

    def test_dataclass_has_fields(self, xs_attribute_code):
        # Credentials type has token field
        assert "token" in xs_attribute_code

    def test_method_receives_dataclass_param(self, xs_attribute_code):
        # GetData takes a Credentials parameter
        assert "Credentials" in xs_attribute_code


class TestOptionalImport:
    def test_optional_imported_when_needed(self, simple_code):
        # simple.wsdl has locale (optional) — Optional must be imported
        assert "from typing import Optional" in simple_code

    def test_no_optional_when_all_required(self):
        # fault_message.wsdl — GetUser has required userId only
        doc = WsdlParser().load(str(FIXTURES / "fault_message.wsdl"))
        code = ClientGenerator(doc).generate("fault_message.wsdl")
        compile(code, "<generated>", "exec")


class TestSoapClientGenerateMethod:
    def test_generate_returns_string(self):
        doc = WsdlParser().load(str(FIXTURES / "simple.wsdl"))
        from soapix.client import SoapClient
        client = SoapClient(str(FIXTURES / "simple.wsdl"), cache=None)
        result = client.generate()
        assert isinstance(result, str)
        assert "UserServiceClient" in result

    def test_generate_writes_file(self, tmp_path):
        from soapix.client import SoapClient
        client = SoapClient(str(FIXTURES / "simple.wsdl"), cache=None)
        out = tmp_path / "client.py"
        result = client.generate(path=str(out))
        assert result is None
        assert out.exists()
        content = out.read_text()
        assert "UserServiceClient" in content
        compile(content, str(out), "exec")
