"""
ClientGenerator — generates a typed Python client class from a WsdlDocument.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from soapix.wsdl.types import ParameterInfo, WsdlDocument

# XSD primitive type → Python type annotation
_XSD_TO_PY: dict[str, str] = {
    "string": "str", "normalizedString": "str", "token": "str", "anyURI": "str",
    "dateTime": "str", "date": "str", "time": "str", "duration": "str",
    "int": "int", "integer": "int", "long": "int", "short": "int", "byte": "int",
    "unsignedInt": "int", "unsignedLong": "int", "unsignedShort": "int", "unsignedByte": "int",
    "float": "float", "double": "float", "decimal": "float",
    "boolean": "bool",
    "base64Binary": "bytes", "hexBinary": "bytes",
    "anyType": "dict", "anySimpleType": "str", "any": "dict",
}


def _strip_prefix(name: str) -> str:
    """Remove namespace prefix: 'tns:Foo' → 'Foo'."""
    return name.split(":", 1)[1] if ":" in name else name


def _safe_identifier(name: str) -> str:
    """Ensure name is a valid Python identifier."""
    import re
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if name and name[0].isdigit():
        name = "_" + name
    return name or "_field"


class ClientGenerator:
    """
    Generates a typed Python client class from a parsed WsdlDocument.

    Usage:
        code = ClientGenerator(doc).generate("http://service/?wsdl")
        Path("client.py").write_text(code)
    """

    def __init__(self, doc: WsdlDocument) -> None:
        self._doc = doc

    def generate(self, wsdl_location: str) -> str:
        """Return the full generated Python source as a string."""
        from soapix.docs.resolver import resolve_input_fields

        # Pass 1 — collect complex types that need @dataclass (topological order)
        complex_types: dict[str, list[ParameterInfo]] = {}
        visited_collect: set[str] = set()
        for op in self._doc.operations.values():
            fields = resolve_input_fields(op, self._doc)
            for f in fields:
                self._collect_complex_types(_strip_prefix(f.type_name), complex_types, visited_collect)

        # Pass 2 — determine which imports are needed
        needs_optional = self._needs_optional()
        needs_dataclass = bool(complex_types)

        lines: list[str] = []

        # Header
        lines += [
            "# Generated by soapix — do not edit manually",
            f"# Source: {wsdl_location}",
            f"# Service: {self._doc.service_name}",
            f"# Generated: {date.today().isoformat()}",
            "",
        ]

        # Imports
        lines.append("from __future__ import annotations")
        if needs_dataclass:
            lines.append("from dataclasses import dataclass")
        if needs_optional:
            lines.append("from typing import Optional")
        lines.append("from soapix import SoapClient")
        lines.append("")

        # Pass 3 — emit @dataclass types
        if complex_types:
            lines.append("")
            lines.append("# --- Types ---")
            lines.append("")
            for type_name, fields in complex_types.items():
                lines += self._emit_dataclass(type_name, fields, complex_types)
                lines.append("")

        # Pass 4 — emit service client class
        class_name = _safe_identifier(self._doc.service_name) + "Client"
        lines.append("")
        lines.append("# --- Client ---")
        lines.append("")
        lines.append(f"class {class_name}:")
        lines.append(f'    def __init__(self, wsdl: str = "{wsdl_location}", **kwargs) -> None:')
        lines.append("        self._client = SoapClient(wsdl, **kwargs)")

        for op_name in sorted(self._doc.operations):
            op = self._doc.operations[op_name]
            lines.append("")
            lines += self._emit_method(op_name, op, complex_types)

        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Type collection
    # ------------------------------------------------------------------

    def _collect_complex_types(
        self,
        type_name: str,
        result: dict[str, list[ParameterInfo]],
        visited: set[str],
    ) -> None:
        """DFS collect complex types in topological order (dependencies first)."""
        if type_name in visited:
            return
        visited.add(type_name)

        from soapix.docs.resolver import get_type_fields
        fields = get_type_fields(type_name, self._doc)
        if not fields:
            return

        # Recurse into children first (topological order)
        for f in fields:
            child = _strip_prefix(f.type_name)
            self._collect_complex_types(child, result, visited)

        # Filter sentinel fields
        real_fields = [f for f in fields if not f.name.startswith("_")]
        if real_fields:
            result[type_name] = real_fields

    # ------------------------------------------------------------------
    # Emission helpers
    # ------------------------------------------------------------------

    def _py_type(self, param: ParameterInfo, complex_types: dict[str, list[ParameterInfo]]) -> str:
        """Return Python type annotation string for a parameter."""
        type_name = _strip_prefix(param.type_name)

        # Check xs:list kind
        key = next((k for k, t in self._doc.types.items() if t.name == type_name), None)
        if key and self._doc.types[key].kind == "list":
            item = self._doc.types[key].item_type or "str"
            inner = _XSD_TO_PY.get(item, "str")
            return f"list[{inner}]"

        # Complex type → dataclass name
        if type_name in complex_types:
            return type_name

        return _XSD_TO_PY.get(type_name, "dict")

    def _annotated_type(
        self,
        param: ParameterInfo,
        complex_types: dict[str, list[ParameterInfo]],
    ) -> str:
        """Return the full annotation including Optional/list wrapping."""
        base = self._py_type(param, complex_types)
        if param.is_list and not base.startswith("list["):
            base = f"list[{base}]"
        if not param.required:
            return f"Optional[{base}]"
        return base

    def _emit_dataclass(
        self,
        type_name: str,
        fields: list[ParameterInfo],
        complex_types: dict[str, list[ParameterInfo]],
    ) -> list[str]:
        lines = ["@dataclass", f"class {type_name}:"]
        # Required fields first, then optional (dataclass ordering requirement)
        required = [f for f in fields if f.required]
        optional = [f for f in fields if not f.required]
        for f in required:
            ann = self._annotated_type(f, complex_types)
            lines.append(f"    {_safe_identifier(f.name)}: {ann}")
        for f in optional:
            ann = self._annotated_type(f, complex_types)
            lines.append(f"    {_safe_identifier(f.name)}: {ann} = None")
        if not required and not optional:
            lines.append("    pass")
        return lines

    def _emit_method(
        self,
        op_name: str,
        op: Any,
        complex_types: dict[str, list[ParameterInfo]],
    ) -> list[str]:
        from soapix.docs.resolver import resolve_input_fields

        fields = resolve_input_fields(op, self._doc)
        fields = [f for f in fields if not f.name.startswith("_")]

        required = [f for f in fields if f.required]
        optional = [f for f in fields if not f.required]

        # Method signature
        sig_parts = ["self"]
        for f in required:
            ann = self._annotated_type(f, complex_types)
            sig_parts.append(f"{_safe_identifier(f.name)}: {ann}")
        for f in optional:
            ann = self._annotated_type(f, complex_types)
            sig_parts.append(f"{_safe_identifier(f.name)}: {ann} = None")

        lines: list[str] = []
        method_name = _safe_identifier(op_name)

        if len(sig_parts) <= 4:
            lines.append(f"    def {method_name}({', '.join(sig_parts)}) -> dict:")
        else:
            lines.append(f"    def {method_name}(")
            lines.append(f"        self,")
            for f in required:
                ann = self._annotated_type(f, complex_types)
                lines.append(f"        {_safe_identifier(f.name)}: {ann},")
            for f in optional:
                ann = self._annotated_type(f, complex_types)
                lines.append(f"        {_safe_identifier(f.name)}: {ann} = None,")
            lines.append("    ) -> dict:")

        if op.documentation:
            doc = op.documentation.replace('"""', "'''")
            lines.append(f'        """{doc}"""')

        # Method body
        has_complex = any(_strip_prefix(f.type_name) in complex_types for f in fields)

        if not fields:
            lines.append(f"        return self._client.service.{op_name}()")
        elif not has_complex:
            # Simple case — all primitives
            lines.append("        return self._client.service." + op_name + "(")
            for f in fields:
                n = _safe_identifier(f.name)
                lines.append(f"            {f.name}={n},")
            lines.append("        )")
        else:
            # Complex types — build kwargs dict
            lines.append("        _kw: dict = {}")
            for f in fields:
                n = _safe_identifier(f.name)
                type_name = _strip_prefix(f.type_name)
                if type_name in complex_types:
                    child_fields = complex_types[type_name]
                    dict_items = ", ".join(
                        f'"{cf.name}": {n}.{_safe_identifier(cf.name)}'
                        for cf in child_fields
                    )
                    if f.required:
                        lines.append(f'        _kw["{f.name}"] = {{{dict_items}}}')
                    else:
                        lines.append(f"        if {n} is not None:")
                        lines.append(f'            _kw["{f.name}"] = {{{dict_items}}}')
                else:
                    if f.required:
                        lines.append(f'        _kw["{f.name}"] = {n}')
                    else:
                        lines.append(f"        if {n} is not None:")
                        lines.append(f'            _kw["{f.name}"] = {n}')
            lines.append(f"        return self._client.service.{op_name}(**_kw)")

        return lines

    def _needs_optional(self) -> bool:
        """Return True if any operation or dataclass field is optional."""
        from soapix.docs.resolver import resolve_input_fields, get_type_fields
        for op in self._doc.operations.values():
            fields = resolve_input_fields(op, self._doc)
            if any(not f.required and not f.name.startswith("_") for f in fields):
                return True
        # Also check complex type fields used as dataclasses
        for type_info in self._doc.types.values():
            if any(not f.required and not f.name.startswith("_") for f in type_info.fields):
                return True
        return False
